-- Verify that data was loaded into bronze tables
SELECT * FROM AIRFLOW_DB.BRONZE.DOCTORS_RAW;
SELECT * FROM AIRFLOW_DB.BRONZE.HOSPITALS_RAW;
SELECT * FROM AIRFLOW_DB.BRONZE.PATIENTS_RAW;
SELECT * FROM AIRFLOW_DB.BRONZE.TREATMENTS_RAW;
SELECT * FROM AIRFLOW_DB.BRONZE.VISITS_RAW;

-- Verify that data was loaded into silver tables
SELECT * FROM AIRFLOW_DB.SILVER.PATIENTS_TRANSFORM;
SELECT * FROM AIRFLOW_DB.SILVER.TREATMENTS_TRANSFORM;
SELECT * FROM AIRFLOW_DB.SILVER.VISITS_TRANSFORM;

-- Verify that data was loaded into gold tables
SELECT * FROM AIRFLOW_DB.GOLD.CITY_HEALTHCARE_ACCESS_AGG;
SELECT * FROM AIRFLOW_DB.GOLD.HOSPITAL_PERFORMANCE_AGG;
SELECT * FROM AIRFLOW_DB.GOLD.PATIENT_VALUE_AGG;
SELECT * FROM AIRFLOW_DB.GOLD.PATIENT_VISIT_SUMMARY_AGG;